### ISSUE TITLE
[BUG] dev 서버 이미지가 내려가는 오류 정상화 - jwt + monitoring.yml 

### ISSUE THREAD

**Issue by pminsung12** [depromeet/SPOT-server#126]
## 📍 재현 위치

- dev 서버에서 발생

![image](https://github.com/user-attachments/assets/7c3fe27a-5efe-43d1-b306-59095e96994e)

## 📌 상황 설명

- 모든 api에 대해서 위의 요청과 같은 오류가 발생. 
- jwt 토큰 부분이라 @wjdwnsdnjs13 트러블 슈팅 중
- #123 

## 🤔 정상 기대값 (선택)

- 모든 api에 대한 정상적인 응답

**Comment by pminsung12** [comment]
#122 로 개발 서버 롤백

**Comment by wjdwnsdnjs13** [comment]
#127 
트러블 슈팅 완료!
accessToken이랑 jwtToken 혼동해서 생긴 오류였어.
Exception도 적용해서 올려놨어
PR 확인하고 어프롭해줘!ㅎㅎ

**Comment by pminsung12** [comment]
상세 트러블슈팅
> accessToken을 넘겨서 검증하는 건데,
Filter Exception 작업하면서 실수로 jwt Token 자체를 넘겼었어.
그래서 혹시나 또 그런 일 생길까봐 파라미터명을 accessToken으로 바꿨구.

**Comment by EunjiShin** [comment]
옹 근데 application-monitoring.yml은 결국 ignore 상태라서 jar 파일에 없는 것 아닌가? 
application-monitoring.yml는 못 불러오는데, yml 내부의 환경 변수는 어떻게 불러오는거지?

**Comment by wjdwnsdnjs13** [comment]
> 옹 근데 application-monitoring.yml은 결국 ignore 상태라서 jar 파일에 없는 것 아닌가? application-monitoring.yml는 못 불러오는데, yml 내부의 환경 변수는 어떻게 불러오는거지?


yml 추가한 게 아니고, 환경 변수 직접 넣은 거 같아
@pminsung12  맞을까??

> -e LOKI_URL=${{ secrets.LOKI_SERVER_URL }} \
https://github.com/depromeet/SPOT-server/pull/130/files#diff-5696ad8fe036727cb6d0f6318015339bc414f05343b1d549c53d8889909a91ba

**Comment by pminsung12** [comment]
@EunjiShin 얍 맞아~ 환경변수 자체를 docker run 에서 -e 옵션으로 주입할 수 있어!

https://docs.docker.com/reference/cli/docker/container/run/#env

**Comment by EunjiShin** [comment]
옹 근데 그럼 로컬에서 실행은 어떻게 해? 지금 다들 로컬에선 도커 없이 그냥 실행 중인거 아닌감?

**Comment by wjdwnsdnjs13** [comment]
.env에 LOKI_URL 추가 해도 될 거 같아.
나는 지금 monitoring.yml 지우고 그렇게 쓰고 있어

**Comment by wjdwnsdnjs13** [comment]
> 옹 근데 그럼 로컬에서 실행은 어떻게 해? 지금 다들 로컬에선 도커 없이 그냥 실행 중인거 아닌감?

.env에 LOKI_URL 추가 해도 될 거 같아.
나는 지금 monitoring.yml 지우고 그렇게 쓰고 있어

**Comment by EunjiShin** [comment]
아 그러네ㅋㅋㅋㅋ 중간부터 .env 쓸 일이 없었어서 완전 잊고 있었다 굿굿 땡큐!! 👍
