### ISSUE TITLE
[고민] 공감(좋아요) 기능 구현 방법

### ISSUE THREAD

**Issue by EunjiShin** [depromeet/SPOT-server#132]
## 💁‍♀️ 고민 사항

- 2차 MVP때 추가되는 '리뷰에 공감했어요(=좋아요)' 기능의 설계 및 구현 방법

### 요구사항
- 유저는 리뷰에 좋아요를 남기거나, 좋아요를 취소할 수 있다.
  - 유저는 자신이 남긴 리뷰에는 좋아요를 누를 수 없다.
  - 유저는 동일 리뷰에 한 번만 공감할 수 있다.
- 유저는 자신이 받은 전체 좋아요 수를 확인할 수 있어야 한다. 
- 리뷰를 좋아요 (공감) 순으로 정렬할 수 있어야 한다.

### 고려사항
- 좋아요 횟수가 카운트 되는 것이 화면에 실시간으로 보여야 해요.
- 따라서, 리뷰 공감순 정렬도 새로고침을 할 때마다 갱신되어야 해요.
- 현재는 없지만, '내가 공감한 리뷰 모아보기' 기능이 생길 수도 있어요.

## ✅ 참고 사항

- 코멘트로 생각한 구현 방법을 하나씩 추가할게요! 하나씩 확인하고 의견 남겨주세요

**Comment by EunjiShin** [comment]
# `0. 전제`

요구사항에 따라, 유저가 어떤 리뷰에 공감했는지 기록을 남겨야 해요. 
따라서 review_likes 테이블을 새롭게 만들고 관리하는 건 필수라고 생각되어서 공통 전제로 깔고 시작할게요.

| 필드명 | 자료형 | 제약사항                | Description              |
|-------------|-----------|-----------------------------|--------------------------|
| id          | BIGINT    | PK, AI | primary key           |
| review_id   | BIGINT    | NN  | review pk            |
| user_id     | BIGINT    | NN    | user pk    |

(created_at, updated_at 생략 & 삭제=좋아요 취소 이므로 soft delete 적용할 필요 없음)

**Comment by EunjiShin** [comment]
# `1. MySQL만 활용하여 구현하기`

## 설명
> review_likes 테이블만을 활용하여 기능을 구현해요.

### 좋아요 프로세스
1. 유저가 리뷰에 좋아요를 남긴다 (API call)
2. review_likes 테이블에 새로운 레코드를 insert 한다.

### 리뷰 정렬 프로세스
1. left join 또는 서브 쿼리를 활용, 블록에 포함된 리뷰를 조회할 때 review_likes 테이블에서 count 연산을 수행하고 이를 이용해 리뷰를 정렬한다. 

## 장점
- 외부 infra 스택 없이 구현 가능
- 서로 다른 유저가 같은 review_likes 레코드에 접근할 일이 없기 때문에 동시성 이슈에서 비교적 자유로움.

## 단점
- 계산 로직 처리 중 부하 발생
  - 요청이 들어올 때마다 review별 공감 수를 count 해야 하므로, 집계 연산이 비싸지고 latency가 길어짐. 
  - 리뷰 공감 수가 변하지 않았다면 count 연산이 불필요하게 중복됨.
  - 유저 수, 리뷰 수, 좋아요 수가 증가할 수록 비용이 계속 커질 것
- 쿼리 복잡도 증가
  - 지금 리뷰 조회하는 쿼리를 보면 이미 꽤 복잡함..! 
  - 여기에 join이나 sub query를 더 추가하는게 좋은 선택인지 잘 모르겠음 🤔

**Comment by EunjiShin** [comment]
# `2. MySQL만 활용하여 구현하되, reviews 테이블에 likes 필드 추가하기`

## ✨ 설명
> review_likes 테이블에서 유저 좋아요 중복 관련 작업을 수행하고, reviews 테이블에 likes_count 필드를 추가해 좋아요 수를 직접 관리해요.

### 좋아요 프로세스
1. 유저가 리뷰에 좋아요를 남긴다 (API call)
2. review_likes 테이블에 새로운 레코드를 insert 한다.
3. reviews.likes_count 필드를 증가시킨다.

### 리뷰 정렬 프로세스
reviews의 likes_count 필드를 이용해 order by 해주면 끝~

## ✨ 장점
- 외부 infra 스택 없이 구현 가능2
- 리뷰 테이블에 좋아요 수가 이미 존재하므로, 불필요한 집계 연산이 필요 없음 (= 방법 1에서 성능 개선한 버전)

## ✨ 단점
- reviews.likes_count의 증감 과정에서 동시성 이슈 발생 가능. 
  - 이때 데이터 정합성 문제가 발생할 수 있으니 batch나 스케줄러 등으로 대사작업 구현 필요
  - 락 거는 과정에서 성능 저하 발생 가능

**Comment by EunjiShin** [comment]
# `3. 2번 방법 + redis 분산락`

## ✨ 설명
> 2번 방법과 전부 동일한데, 동시성 이슈 보완을 위해 어플리케이션 락인 분산락을 적용한다.

### 좋아요 프로세스
1. 유저가 리뷰에 좋아요를 남긴다 (API call)
2. redis를 활용해 락을 획득한다.
3. review_likes 테이블에 새로운 레코드를 insert 한다.
4. reviews.likes_count 필드를 증가시킨다.
5. 락을 반환한다.

### 리뷰 정렬 프로세스
reviews의 likes_count 필드를 이용해 order by 해주면 끝~22

## ✨ 장점
- redis를 활용하므로 DB락인 비관적락 등에 비해 성능이 좋다.
- 서버나 DB 등이 분산될 상황을 가정하면 (스케일아웃이나...primary-secondary DB라던가..)유리한 방법이다.

## ✨ 단점
- redis를 추가로 사용해야 하고, 분산락 구현이 필요하다.
- 정말정말 동시성에 예민하게 처리할거라면 분산락과 비관적락을 동시에 사용하는 것도 고려해야 한다. ([토스](https://www.youtube.com/watch?v=UOWy6zdsD-c)가 글케 한다고 합니다)
  - 하지만 우리에게 고려사항일지는..?

**Comment by EunjiShin** [comment]
~~ 인 마이 어피니언 ~~

SPOT 서비스의 트래픽과 개발 리소스를 고려했을 때, **3번 방법이 제일 적합**할 것 같음!
2번 방법도 충분히 간단하고 효율적이지만, 아키텍처 확장이나 공부 목적(사이드플젝이니까ㅎ.ㅎ)으로 분산락을 적용해봐도 문제 없는 상황이라고 판단했어~ (redisson 라이브러리 사용하면 구현 난이도가 그렇게 높지 않기도 하고)

우리가 mysql 8.0 버전을 사용하니 Materialized view를 이용하거나, 메세지큐를 활용해 비동기 방식으로 구현할 수도 있겠으나...... 그쯤되면 더 이상 기능 구현이 주가 아닐 것 같아서 😅 일단은 위의 저 방법들만 고려했다! 

이제 @pminsung12 @wjdwnsdnjs13 의견 받고, 이견 없으면 작업 고고할게잉

**Comment by wjdwnsdnjs13** [comment]
내가 좋아요 구현할 때엔 1, 2번 밖에 안 해보긴 했는데
확실히 2번은 동시성 이슈가 있긴 하더라구

>2번 방법도 충분히 간단하고 효율적이지만, 아키텍처 확장이나 공부 목적(사이드플젝이니까ㅎ.ㅎ)으로 분산락을 적용해봐도 문제 없는 상황이라고 판단했어~ (redisson 라이브러리 사용하면 구현 난이도가 그렇게 높지 않기도 하고)

이런 거라면 3번 나도 동의!

근데, 궁금한 거 한 가지는 리뷰가 삭제되었을 때엔 좋아요는 어떻게 처리할 예정이야??
soft 딜리트라 좋아요는 건들지 않고 놔두는 게 나으려나??

**Comment by pminsung12** [comment]
와 갓은지... 정리가 진짜 👍 👍 👍 👍 👍 👍 
나는 2번, 3번을 고민을 좀 해봤는데 우리 지금 앱의 규모나 지출 등을 고려했을 때 2번이 제일 나은 것 같더라고.
그런데 확장성과 공부를 위해서~ **나도 3번으로 진행하면 제일 좋을 것 같아~**. (비용만 괜찮다면..!)

**Comment by EunjiShin** [comment]
@wjdwnsdnjs13 

> 근데, 궁금한 거 한 가지는 리뷰가 삭제되었을 때엔 좋아요는 어떻게 처리할 예정이야??

이거는 이슈내용이랑은 무관한 주제인 것 같아서.. 따로 스레드 팔게! 
소프트딜리트 목적이 백업이냐, 내부 데이터 수집 용도냐에 따라 달라질 것 같으니 디자인 파트도 확인해보아야 할 것 같아~

**Comment by EunjiShin** [comment]
@pminsung12 

> (비용만 괜찮다면..!)
얍 그래서 redis를 어떻게 세팅할 것인지 한번 찾아보고, 예상 견적 짜서 작업 시작 전에 먼저 공유할게! 
만약 금액이 에바라면 2번 방안으로 유턴하면 될듯~

> p.s.)

비슷해~ 배치 작업은 일괄적으로 대량의 작업을 처리하는 방식이고, spring batch는 그런 배치 작업을 스프링 프레임워크에서 제공해주는거야.
@Scheduler 대신 spring batch를 굳이 쓰는 이유는, spring batch에 이것저것 이점이 있어서! 
(스케줄러는 정해진 시간에 자동으로 동작하고, 개발자가 직접 실행할 수 없지만 배치는 개발자가 컨트롤 가능 & 실패한 작업이 있다면 그 작업부터 재시작 가능 등등..)

**Comment by EunjiShin** [comment]
<img width="1221" alt="스크린샷 2024-08-14 오후 8 39 21" src="https://github.com/user-attachments/assets/ed62bebe-fe0d-482e-828f-254c1d7c81cc">

aws elastiCache (redis oss)를 cache.t2micro로 사용할 경우 750시간 free-tier 사용 가능함을 확인 
논클러스터 모드를 이용, 단일 노드로 띄우면 충분히 비용 문제 없이 활용 가능할 것으로 판단

=> 3번 방법으로 진행 확정 땅땅! @pminsung12 @wjdwnsdnjs13

**Comment by EunjiShin** [comment]
((( 좋아요 수만 관리하는 테이블 따로 관리하는 방법, redis의 pub/sub 이용해서 batch 대신 쓰는 방법, 이벤트 활용하는 방법 등등... 다양하게 고민해보자 )))
