### ISSUE TITLE
[BUG] M1에서 Embedded redis가 동작하지 않는 이슈

### ISSUE THREAD

**Issue by EunjiShin** [depromeet/SPOT-server#173]
## 📍 재현 위치

- 실행 환경 : MacOS - ARM Mac (M1)
- 버그 제보자 : @pminsung12 
- 문제 코드 :` EmbeddedRedisConfig`

## 📌 상황 설명

- 비어있는 포트를 사용했는데도 redis 서버를 실행할 수 없어요.
- windows, mac(m2) 사용자 모두에게서 정상적으로 실행되었으나, m1 사용자에게선 실행되지 않았아요.

## ✅ 원인

```
    private void initExecutables() {
        executables.put(OsArchitecture.WINDOWS_x86, "redis-server-2.8.19.exe");
        executables.put(OsArchitecture.WINDOWS_x86_64, "redis-server-2.8.19.exe");

        executables.put(OsArchitecture.UNIX_x86, "redis-server-2.8.19-32");
        executables.put(OsArchitecture.UNIX_x86_64, "redis-server-2.8.19");

        executables.put(OsArchitecture.MAC_OS_X_x86, "redis-server-2.8.19.app");
        executables.put(OsArchitecture.MAC_OS_X_x86_64, "redis-server-2.8.19.app");
    }
```
- 출처 : https://github.com/ozimov/embedded-redis/blob/master/src/main/java/redis/embedded/RedisExecProvider.java 
- 사용 중인 embedded redis 라이브러리에서 mac_arm64 용 바이너리가 준비되지 않은 상태에요.
  - m2인 본인...왜...되는건지.....? ㅠ?

## 🤔 해결 방법

1. 당장 서버 실행이 안되는 @pminsung12 은 일단 local/test에서 embedded redis를 사용하지 않고, 직접 redis 설치하여 사용해요.
2. 그동안 [여기 블로그](https://velog.io/@hakjong/ARM-Mac-M1-%EC%97%90%EC%84%9C-embedded-redis-%EC%82%AC%EC%9A%A9)를 참고하여 arm Mac에서 쓸 수 있는 레디스 바이너리 파일을 사용하도록 코드를 추가해요.

**Comment by EunjiShin** [comment]
resolve by #172

**Comment by pminsung12** [comment]
### 원인
- 임베디드 redis 라이브러리에서 mac_arm64 용 바이너리가 준비되지 않은 것이 원인인 것을 알 수 있다.

---
### 해결
- wget으로 레디스 바이너리 파일을 직접 설치해 프로젝트에 추가하고 경로 설정함.
- 그리고 실행 주체가 arm mac인지 확인하는 메서드 추가
- 바이너리 파일을 프로젝트에 추가하는게 맞겠지만~ 어차피 나만쓰고 또 내 노트북(M1)에서만 바이너리파일이 필요하기 때문에 gitignore했음.
- 민감한 정보라 ignore한 것 아님! 올라가도 상관은 없음.
