### ISSUE TITLE
[REPORT] 블럭 좌석 범위 엣지케이스 발견

### ISSUE THREAD

**Issue by EunjiShin** [depromeet/SPOT-server#60]
## 📌 상황 설명

**[ AS-IS ]**
<img width="550" alt="스크린샷 2024-07-19 오후 11 41 21" src="https://github.com/user-attachments/assets/e4ed356c-becd-46fb-9e9b-e6cbdab3c447">
- 블록별 좌석 번호가 위 사진과 같이 순차적으로 이어질 것이라고 생각
- 열별 min, max 값을 클라에게 주면 -> 사용자가 입력한 좌석 번호가 해당 열에 존재하는지 range 조건을 이용해 판별
  - `e.g., 2열은 5번 ~ 18번 좌석이 있음 :: 사용자가 2열 20번 입력하면 exception`
- 사용자가 텍스트 박스를 입력할 때마다 API를 call 하면 비효율적이라고 생각되어 위와 같이 설계
<br>

**[ 문제 상황 ]**
<img width="1086" alt="스크린샷 2024-07-19 오후 11 44 25" src="https://github.com/user-attachments/assets/c226810c-c904-4272-976f-b44971510747">
<img width="1073" alt="스크린샷 2024-07-19 오후 11 44 45" src="https://github.com/user-attachments/assets/c15e719c-7609-49e3-bc8f-3a3450142697">
- 위와 같이, 동일 라인에서 좌석 번호가 이어지지 않는 경우가 존재
  - `e.g., 1열은 241-244, 217-220, 193-196, .... `
- 현재와 같은 min, max range로는 커버 불가능
  - `e.g., 1열 min = 196, max = 244라고 두면, 230같이 범위에는 포함되지만 실제로는 존재하지 않는 좌석을 거를 수 없음`
  
<br>

**[ 해결 방법 제안 ]**
- range List를 보내서 체크하게 하기 :: `[ (241, 244), (217, 220), ... ] `
  - 장점 : API 하나로 모든 예외 커버 가능
  - 단점 : DB 모델링, 블럭 좌석과 관련된 일부 API 일괄 수정 필요 (maxNumber가 무의미해짐)

- 사용자가 좌석 번호 입력할 때마다 API call해서 체크하기 
  - 장점 : 제일 직관적이고 구현이 쉬움
  - 단점 : API 호출 횟수 증가 (번호 수정할 때마다 요청)

**Comment by EunjiShin** [comment]
@pminsung12 @wjdwnsdnjs13 위 두 가지 방법을 고민 중인데, 둘 생각은 어때? 저 방법들 말고 다른 방법 제안해줘도 좋고!!

**Comment by pminsung12** [comment]
> 사용자가 좌석 번호 입력할 때마다 API call해서 체크하기

입력이라는 게 "완료"라는 제출버튼을 누르기 전에 박스에 사용자가 입력하는 keydown 이벤트를 계속 감시하면서 api 요청을 보내는 방법을 얘기하는 거 맞아?

![image](https://github.com/user-attachments/assets/1d6d1f35-7a08-4cf9-bdba-7f533a2b26eb)

**Comment by EunjiShin** [comment]
@pminsung12 아니! 완료 버튼을 눌렀을때를 의도했어~

**Comment by pminsung12** [comment]
나는 플로우 상 사용자가 느끼기에는 완료버튼을 누르기 전에 앱 상에서 검증을 해주면 좋을 것 같다는 의견 한표 ..!

**Comment by EunjiShin** [comment]
@pminsung12 그럼 일단은 출시 일정내 수정을 위해서 2안으로 진행하고, 이후 1안으로 최적화하는 방향으로 진행할게! 

대신 2안으로 진행할 땐, 유저 레이턴시를 고려해서 캐싱을 적용해둘게
(블록별 좌석 번호는 변하지 않을 것으로 예상되는 값 - 경기장에서 좌석을 추가하거나, 기존 좌석을 변경하거나, 좌석을 없애는 이벤트가 현재까진 발생한 적 없음)

**Comment by EunjiShin** [comment]
여기 스레드에서 논의한 결과, 클라이언트쪽 로직 문제로 1차 MVP에선 3안 이용하기로 결정

**[ 3안 내용 ]** 
- 열별 좌석 번호 리스트를 넘겨주면 클라에서 contains을 이용해 예외 처리

```
[ AS-IS ]
1열 min=1, max=10

[ TO-BE ]
1열 [1,2,3,4,5,6,7,8,9.10]
```

단, 특정 블럭 내의 좌석을 조회할 땐 크게 문제 없으나 (maxium 400석 이하) 구역 단위로 조회할 땐 메모리 이슈 발생할 수 있음!
이후 모니터링 & 구역별 최대 좌석수 찾아보고 API 성능 개선 진행 예정
