### ISSUE TITLE
윈도우에서 동작 시 makeGitHooksExecutable 문제

### ISSUE THREAD

**Issue by wjdwnsdnjs13** [depromeet/SPOT-server#8]
# 문제 상황
- 윈도우에서 SpotApplication 실행 혹은 build 시 에러가 발생해.
![image](https://github.com/depromeet/SPOT-server/assets/67488973/6477d078-f331-45f5-9d0f-f8a194588b8e)

# 원인
- chmod가 윈도우에서 동작하지 않는 명령어라서 그런 거 같아. 어제 할 땐 커밋이라 상관 없었던 거 같아.
  - 지금 생각해보니 빌드만이 문제가 아니고, 애플리케이션 실행할 때 마다 에러가 뜨긴 할 거 같아.
  - 도커하면서 정상 동작하는지 보려고 하는 데, 계속 에러가 발생해서 애를 좀 먹었다..ㅎㅎ;
  - build는 bash 등으로 하면 되긴하는데, 실행이 문제...!

# 해결 방법
```Java
tasks.register<Exec>("makeGitHooksExecutable") {
        commandLine("attrib", "+x", "${rootProject.rootDir}/.git/hooks/pre-commit")
        dependsOn("updateGitHooks")
    }
```
- chmod 대신 attrib 명령어로 고치면 해결 자체는 돼!ㅎㅎ ( 이 간단한 걸... 하루 종일 헤맸다 ㅠㅠ)

# 제안
```Java
tasks.register<Exec>("makeGitHooksExecutable") {
        commandLine("chmod", "+x", "${rootProject.rootDir}/.git/hooks/pre-commit")
        dependsOn("updateGitHooks")
    }
```
에서 다음 코드로 수정하면 될 거 같은 데 어때??

```Java
tasks.register<Exec>("makeGitHooksExecutable") {
      if (System.getProperty("os.name").contains("Windows")) {
          commandLine("attrib", "+x", "${rootProject.rootDir}/.git/hooks/pre-commit")
      } else {
          commandLine("chmod", "+x", "${rootProject.rootDir}/.git/hooks/pre-commit")
      }
      dependsOn("updateGitHooks")
  }
```

**Comment by EunjiShin** [comment]
옹 윈도우에 chmod 없는거 이번에 첨 알았네... OS 이슈가 있었구만
위에 보내준 코드 잘 동작하면 바로 PR로 올려주면 될 듯해~!

**Comment by wjdwnsdnjs13** [comment]
> 옹 윈도우에 chmod 없는거 이번에 첨 알았네... OS 이슈가 있었구만 위에 보내준 코드 잘 동작하면 바로 PR로 올려주면 될 듯해~!

오키 근데, 맥에서도 저렇게 수정하면
