### ISSUE TITLE
[제안] Caffeine을 이용한 로컬 캐시 세팅

### ISSUE THREAD

**Issue by EunjiShin** [depromeet/SPOT-server#88]
## 💁‍♀️ 제안 사항

- 오픈소스 캐시 라이브러리인 Caffeine을 이용해 로컬 캐시를 설정해요.

## 👀 제안 이유

- 블럭별 좌석 정보 조회 등, **자주 조회되는데 변동 가능성은 거의 없는 데이터에 캐시를 적용해 조회 성능을 최적화 하기 위해서** 제안해요.
- Redis 등 글로벌 캐시를 사용하지 않고 로컬 캐시를 제안하는 이유
  - 현재 서비스에서 캐시를 적용할 데이터가 그리 많지 않아요. (종류도, 실제 데이터 양도)
  - 캐시 외에 Redis 사용이 필요한 기능도 없어요.
  - (현재) 단일 서버 단일 DB라서, 서버 인스턴스간의 캐시 데이터 동기화 이슈도 발생하지 않아요.
  - 해커톤 전에 빠르게 캐시 적용을 완료하고 싶어요.
  - `따라서 좌석 조회 최적화를 위해 Redis 인스턴스를 세팅하는건, 비용 & 세팅 & 학습 면에서 오버 엔지니어링이라고 생각해요. `
    - 금전적 비용 측면에선, MemoryDB for Redis 대신 AWS ElastiCache를 사용하면 프리티어를 사용할 수 있긴 합니다. 참고!

## ✅ 참고 사항

- 널리 알려진 EhCache와 Caffeine 중 무엇을 사용할지 고민하면서 각각의 캐시를 조사했어요. 궁금하다면 [링크](https://eunji-shin.notion.site/EhCache-vs-Caffeine-db9168caa344460eb4d3642f6e91d8dc?pvs=4)를 참고해주세요!
- 나중에 글로벌 캐시가 필요해지면 그때 다시 redis 도입을 검토해보면 좋을 것 같아요~!

**Comment by wjdwnsdnjs13** [comment]
누나가 말한대로 단일 서버라서 글로벌 캐시 사용이 굳이 인 거 같구 카페인으로 로컬 캐시 사용에 동의!

캐시 사용은 처음이라 궁금한 점인데,
Redis는 spring 애플리케이션에 큰 영향을 주지 않는 것으로 알고 있는데,
로컬 캐시는 인스턴스 리소스를 잡아먹어서 spring 애플리케이션의 성능? 서버 인스턴스의 성능?을 저하시킬 수 있지 않아??
우리가 적은 가격에 사용하려고 서버 인스턴스를 최하위로 잡는 거로 알고 있는데 크게 지장은 없는 거야?
(한 번도 사용해본 적이 없어서 단순 궁금증...!ㅎㅎ)

**Comment by EunjiShin** [comment]
@wjdwnsdnjs13 

웅 마자 근데 본문에서 언급한 것처럼, 우리가 캐시를 적용할 데이터가 종류도 적고 양도 적어
(1차 MVP 기준, 잠실 경기장의 블럭별 좌석 번호 범위)

만약 seat object를 그대로 캐싱한다면 메모리 점유율이 높아질 순 있겠으나, 좌석 번호 필드만 저장할 거라서 메모리 릭 발생할 정도의 양은 아니라고 판단했어~ 

기능 적용하고 바로 유저에게 배포되는게 아니니까, 우리끼리 리소스 모니터링 해보고 에바다 싶음 그때 롤백해도 괜찮을듯!
